name: Build HTML Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y emacs-nox make git

    - name: Clone org-mode repository
      run: |
        git clone https://git.savannah.gnu.org/git/emacs/org-mode.git /tmp/org-mode
        cd /tmp/org-mode
        make autoloads

    - name: Build HTML documentation
      run: |
        export EMACSLOADPATH="/tmp/org-mode/lisp:$EMACSLOADPATH"
        cd docs
        make html

    - name: Upload HTML documentation as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html
